### ISSUE TITLE
`Core:range` の説明文が無い

### ISSUE THREAD

**Issue by kakkokari-gtyih** [aiscript-dev/aiscript-dev.github.io#11]
https://aiscript-dev.github.io/ja/references/builtin-props.html で使用されているものの、説明文が https://aiscript-dev.github.io/ja/references/std.html#core にない

もしかしたら`Core`系が足りてないかも

**Comment by FineArchs** [comment]
`Core`系で記載されていないのは`Core:ai`、`Core:range`、演算子系（`Core:and`など）ですね。
`Core:ai`は隠しでもいいとして、`Core:range`は必要、演算子系も一応書いた方がいいかも？（量が多いので枠を作った方がいいかもです）

**Comment by kakkokari-gtyih** [comment]
演算子系はここに説明がある https://aiscript-dev.github.io/ja/references/syntax.html#%E6%BC%94%E7%AE%97%E5%AD%90%E4%B8%80%E8%A6%A7 のでリンクで良さそう
